export const Types = {
    ABOUT_REQUESTED: 'ABOUT_REQUESTED',
    ABOUT_FULFILLED: 'ABOUT_FULFILLED',
    ABOUT_REJECTED: 'ABOUT_REJECTED',
    GAMES_REQUESTED: 'GAMES_REQUESTED',
    GAMES_FULFILLED: 'GAMES_FULFILLED',
    GAMES_REJECTED: 'GAMES_REJECTED',
    CONTACT_FORM_SUBMITTED: 'CONTACT_FORM_SUBMITTED',
};